services:
  # Kafka 서비스
  kafka-0:
    image: bitnami/kafka:3.7
    container_name: kafka-0
    ports:
      - '9094:9094' # Kafka 외부 액세스 포트
    environment:
      KAFKA_KRAFT_CLUSTER_ID: z6sXmGHyR1qVTyyl9XXr0g
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-volume-0:/bitnami
    networks:
      - kafka-network

  # k6
  k6:
    image: grafana/k6:latest
    container_name: k6
    command: run -o output-influxdb=http://influxdb:8086/mydb /scripts/test-script.js # 수정된 부분
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb
    networks:
      - kafka-network

  # influxdb
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
    - "8086:8086"
    environment:
    - INFLUXDB_DB=k6
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
    - ./docker-volumes/influxdb/data:/var/lib/influxdb
    networks:
    - kafka-network
    
  # prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kafka-network

  # grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      - prometheus
    networks:
      - kafka-network

volumes:
  kafka-volume-0:
  influxdb-data:
  grafana-data:

networks:
  kafka-network:
